# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Glearn < Formula
  desc "Long description for glearn-cli"
  homepage ""
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Galvanize-IT/glearn-cli/releases/download/v0.1.4/glearn-cli_0.1.4_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "88c08eff38c252194cc3159ae2991c426af3958168810df1094f350d3e0c627b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Galvanize-IT/glearn-cli/releases/download/v0.1.4/glearn-cli_0.1.4_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "65b878e5de66633eb8dad33edebf2187ff5e42dd86b8825e2266f4f9646b3005"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "glearn"
  end
end
