# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Glearn < Formula
  desc "Long description for glearn-cli"
  homepage ""
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Galvanize-IT/glearn-cli/releases/download/v0.1.3/glearn-cli_0.1.3_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b0d437c5fb7b7a0dd6ef8cdca460d34723860477b2a0c7660a65d7f3ce000a73"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Galvanize-IT/glearn-cli/releases/download/v0.1.3/glearn-cli_0.1.3_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "071970387864028f6b9ec54499b948b08365ad88458e78444c9e8ea2a1a9de07"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "glearn"
  end
end
