# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Glearn < Formula
  desc "Long description for glearn-cli"
  homepage ""
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Galvanize-IT/glearn-cli/releases/download/v0.2.1/glearn-cli_0.2.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "57ca8a5d5957e9795c0a8c480a0b4b7077a8124db640c06764bc65db06210aa9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Galvanize-IT/glearn-cli/releases/download/v0.2.1/glearn-cli_0.2.1_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4d869557f8550c39ab3d04a8ce9f5da33da7a9a2fc6d8d32fc4d3d823d232660"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "glearn"
  end
end
