# This file was generated by GoReleaser. DO NOT EDIT.
class Learn < Formula
  desc "Learn curriculum publishing tool © Galvanize, Inc."
  homepage ""
  version "0.8.19"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gSchool/glearn-cli/releases/download/v0.8.19/glearn-cli_0.8.19_Darwin_x86_64.tar.gz"
    sha256 "6fa5bd39ff55c37fc813b460b593a654ce5bd2843fd784d3427495e2074bfd31"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gSchool/glearn-cli/releases/download/v0.8.19/glearn-cli_0.8.19_Linux_x86_64.tar.gz"
      sha256 "6f81a4cffe12af88e06c35964bc37b31729e10762758217e942374026b145bcb"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "learn"
  end
end
