# This file was generated by GoReleaser. DO NOT EDIT.
class Learn < Formula
  desc "Learn curriculum publishing tool © Galvanize, Inc."
  homepage ""
  version "0.6.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gSchool/glearn-cli/releases/download/v0.6.4/glearn-cli_0.6.4_Darwin_x86_64.tar.gz"
    sha256 "e699f26298a85283282d65c5b1d5cf97ebff403127c57b04ae7efb6d862145a1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gSchool/glearn-cli/releases/download/v0.6.4/glearn-cli_0.6.4_Linux_x86_64.tar.gz"
      sha256 "0629aeb0c9266fac0cca98be5a5a6e783318daf1afd081e142323056c1fe688c"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "learn"
  end
end
