# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Learn < Formula
  desc "Learn curriculum publishing tool © Galvanize, Inc."
  homepage ""
  version "0.10.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gSchool/glearn-cli/releases/download/v0.10.2/glearn-cli_0.10.2_Darwin_arm64.tar.gz"
      sha256 "e785a1b6fc9e3c1b2fedcb4cfb5079fbfd80745db18d98b77636e51a72bf463d"

      def install
        bin.install "learn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gSchool/glearn-cli/releases/download/v0.10.2/glearn-cli_0.10.2_Darwin_x86_64.tar.gz"
      sha256 "c811f305f0c51edfa08a4e9b8a6b18f9f4fdb038005266e8cb57645164b88558"

      def install
        bin.install "learn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gSchool/glearn-cli/releases/download/v0.10.2/glearn-cli_0.10.2_Linux_arm64.tar.gz"
      sha256 "e02ac70ce4eb52085540f1d2108086b9f1b6454d189042ef2cb78a3c805a3910"

      def install
        bin.install "learn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gSchool/glearn-cli/releases/download/v0.10.2/glearn-cli_0.10.2_Linux_x86_64.tar.gz"
      sha256 "d9e32592c836afa4ec05bca2abacc127d5d7b06a6e8fed78638da0c4e9c81519"

      def install
        bin.install "learn"
      end
    end
  end

  depends_on "git"
  depends_on "zsh"
end
